package types

const (
	MsgValidator      = "This node is a validator"
	MsgP2pNodeID      = "P2P Node ID"
	MsgSignedProposal = "Signed proposal"

	MsgAddingVote                    = "Adding vote"
	MsgAddedVoteToPrevote            = "Added vote to prevote"
	MsgAddedVoteToPrecommit          = "Added vote to precommit"
	MsgAddedVoteToLastPrecommits     = "Added vote to last precommits"
	MsgSendingVoteMessage            = "Sending vote message"
	MsgSend                          = "Send"
	MsgReceive                       = "Receive"
	MsgReadPacketMsg                 = "Read PacketMsg"
	MsgTrySend                       = "TrySend"
	MsgReceivedBytes                 = "Received bytes"
	MsgReceivedProposal              = "Received proposal"
	MsgReceiveBlockPart              = "Receive block part"
	MsgReceivedCompleteProposalBlock = "Received complete proposal block"

	// Consensus messages
	MsgEnteringNewRound                         = "Entering new round"
	MsgEnteringNewRoundWithInvalidArgs          = "Entering new round with invalid args"
	MsgEnteringProposeStep                      = "Entering propose step"
	MsgEnteringProposeStepWithInvalidArgs       = "Entering propose step with invalid args"
	MsgProposeStepTurnToPropose                 = "Propose step; our turn to propose"
	MsgProposeStepNotTurnToPropose              = "Propose step; not our turn to propose"
	MsgEnteringPrevoteStep                      = "Entering prevote step"
	MsgEnteringPrevoteStepWithInvalidArgs       = "Entering prevote step with invalid args"
	MsgEnteringPrevoteWaitStep                  = "Entering prevote wait step"
	MsgEnteringPrevoteWaitStepWithInvalidArgs   = "Entering prevote wait step with invalid args"
	MsgEnteringPrecommitStep                    = "Entering precommit step"
	MsgEnteringPrecommitStepWithInvalidArgs     = "Entering precommit step with invalid args"
	MsgEnteringPrecommitWaitStep                = "Entering precommit wait step"
	MsgEnteringPrecommitWaitStepWithInvalidArgs = "Entering precommit wait step with invalid args"
	MsgEnteringCommitStep                       = "Entering commit step"
	MsgEnteringCommitStepWithInvalidArgs        = "Entering commit step with invalid args"
	MsgFinalizingCommitOfBlock                  = "Finalizing commit of block"
	MsgCommittedBlock                           = "Committed block"
	MsgUpdatingValidBlock                       = "Updating valid block because of POL"
	MsgLockingBlock                             = "Precommit step: +2/3 prevoted proposal block; locking"
	MsgScheduledTimeout                         = "Scheduled timeout"
)
